{{- if .Values.persistence.cache.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jellyfin.fullname" . }}-cache
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "jellyfin.labels" . | nindent 4 }}
    volume: cache
spec:
  accessModes:
    - {{ .Values.persistence.cache.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.cache.size }}
  {{- if .Values.persistence.cache.storageClass }}
  storageClassName: {{ .Values.persistence.cache.storageClass }}
  {{- end }}
{{- end }}
