apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "sabnzbd.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "sabnzbd.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.sabnzbd.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
