apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grafana.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.grafana.replicaCount }}
  selector:
    matchLabels:
      {{- include "grafana.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "grafana.selectorLabels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/datasources: {{ include (print $.Template.BasePath "/configmap-datasources.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "grafana.serviceAccountName" . }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 472
        runAsGroup: 472
        fsGroup: 472
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image.repository }}:{{ .Values.grafana.image.tag }}"
          imagePullPolicy: {{ .Values.grafana.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.grafana.service.targetPort }}
              protocol: TCP
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "grafana.fullname" . }}-secret
                  key: admin-password
          {{- if .Values.grafana.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: /grafana/api/health
              port: http
            initialDelaySeconds: {{ .Values.grafana.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.grafana.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.grafana.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.grafana.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.grafana.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: /grafana/api/health
              port: http
            initialDelaySeconds: {{ .Values.grafana.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.grafana.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.grafana.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.grafana.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.grafana.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
            - name: datasources
              mountPath: /etc/grafana/provisioning/datasources
            - name: dashboards-provider
              mountPath: /etc/grafana/provisioning/dashboards
            {{- if .Values.dashboards.kubarrOverview.enabled }}
            - name: dashboards
              mountPath: /var/lib/grafana/dashboards
            {{- end }}
            - name: data
              mountPath: /var/lib/grafana
      volumes:
        - name: config
          configMap:
            name: {{ include "grafana.fullname" . }}-config
        - name: datasources
          configMap:
            name: {{ include "grafana.fullname" . }}-datasources
        - name: dashboards-provider
          configMap:
            name: {{ include "grafana.fullname" . }}-dashboards-provider
        {{- if .Values.dashboards.kubarrOverview.enabled }}
        - name: dashboards
          configMap:
            name: {{ include "grafana.fullname" . }}-dashboards
        {{- end }}
        - name: data
          {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "grafana.fullname" . }}-data
          {{- else }}
          emptyDir: {}
          {{- end }}
