apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grafana.fullname" . }}-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "grafana.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.grafana.adminPassword }}
  admin-password: {{ .Values.grafana.adminPassword | b64enc | quote }}
  {{- else }}
  admin-password: {{ randAlphaNum 16 | b64enc | quote }}
  {{- end }}
