apiVersion: v1
kind: Service
metadata:
  name: {{ include "victoriametrics.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "victoriametrics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.victoriametrics.service.type }}
  ports:
    - port: {{ .Values.victoriametrics.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "victoriametrics.selectorLabels" . | nindent 4 }}
