apiVersion: v1
kind: Service
metadata:
  name: {{ include "qbittorrent.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "qbittorrent.labels" . | nindent 4 }}
  {{- with .Values.qbittorrent.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.qbittorrent.service.type }}
  ports:
    - port: {{ .Values.qbittorrent.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "qbittorrent.selectorLabels" . | nindent 4 }}
