{{- if and .Values.jellyseerr.oauth.enabled .Values.jellyseerr.oauth.clientSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jellyseerr.oauth.secretName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "jellyseerr.labels" . | nindent 4 }}
type: Opaque
stringData:
  client-secret: {{ .Values.jellyseerr.oauth.clientSecret | quote }}
{{- end }}
