apiVersion: v2
name: transmission
description: A Helm chart for Transmission - Fast, easy BitTorrent client
type: application
version: 0.1.0
appVersion: "4.0"
keywords:
  - transmission
  - bittorrent
  - download
  - torrent
  - media
home: https://transmissionbt.com/
sources:
  - https://github.com/transmission/transmission
maintainers:
  - name: Kubarr Team
