apiVersion: v1
kind: Service
metadata:
  name: {{ include "loki.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "loki.labels" . | nindent 4 }}
spec:
  type: {{ .Values.loki.service.type }}
  ports:
    - port: {{ .Values.loki.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "loki.selectorLabels" . | nindent 4 }}
