apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rutorrent.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "rutorrent.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.rutorrent.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
