apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rutorrent.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "rutorrent.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.rutorrent.replicaCount }}
  selector:
    matchLabels:
      {{- include "rutorrent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rutorrent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rutorrent.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: rutorrent
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.rutorrent.image.repository }}:{{ .Values.rutorrent.image.tag }}"
          imagePullPolicy: {{ .Values.rutorrent.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.rutorrent.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "rutorrent.fullname" . }}-config
          {{- if .Values.rutorrent.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.rutorrent.livenessProbe.tcpSocket.port }}
            initialDelaySeconds: {{ .Values.rutorrent.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.rutorrent.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.rutorrent.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.rutorrent.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.rutorrent.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: {{ .Values.rutorrent.readinessProbe.tcpSocket.port }}
            initialDelaySeconds: {{ .Values.rutorrent.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.rutorrent.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.rutorrent.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ .Values.rutorrent.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.rutorrent.resources | nindent 12 }}
          volumeMounts:
            {{- if .Values.persistence.config.enabled }}
            - name: config
              mountPath: {{ .Values.persistence.config.mountPath }}
            {{- end }}
            {{- if .Values.storage.hostPath.enabled }}
            - name: downloads
              mountPath: /downloads
            {{- end }}
      volumes:
        {{- if .Values.persistence.config.enabled }}
        - name: config
          persistentVolumeClaim:
            claimName: {{ include "rutorrent.fullname" . }}-config
        {{- end }}
        {{- if .Values.storage.hostPath.enabled }}
        - name: downloads
          hostPath:
            path: {{ .Values.storage.hostPath.rootPath }}/downloads/rutorrent
            type: DirectoryOrCreate
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
