{{- if .Values.persistence.downloads.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "deluge.fullname" . }}-downloads
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "deluge.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.downloads.accessMode }}
  {{- if .Values.persistence.downloads.storageClass }}
  storageClassName: {{ .Values.persistence.downloads.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.downloads.size }}
{{- end }}
