apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "plex.fullname" . }}-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.plex.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if .Values.plex.claimToken }}
  PLEX_CLAIM: {{ .Values.plex.claimToken | quote }}
  {{- end }}
