{{- if .Values.persistence.transcode.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "plex.fullname" . }}-transcode
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "plex.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.transcode.accessMode }}
  {{- if .Values.persistence.transcode.storageClass }}
  storageClassName: {{ .Values.persistence.transcode.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.transcode.size }}
{{- end }}
