apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauth2-proxy
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: oauth2-proxy-secret-reader
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["oauth2-proxy-credentials"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: oauth2-proxy-secret-reader
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oauth2-proxy-secret-reader
subjects:
  - kind: ServiceAccount
    name: oauth2-proxy
    namespace: {{ .Values.namespace.name }}
