apiVersion: v1
kind: Service
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 4180
      protocol: TCP
      name: http
  selector:
    {{- include "oauth2-proxy.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}-nginx
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
    app.kubernetes.io/component: nginx
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "oauth2-proxy.name" . }}-nginx
    app.kubernetes.io/instance: {{ .Release.Name }}
