apiVersion: v1
kind: Service
metadata:
  name: {{ include "oauth2-proxy.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "oauth2-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 4180
      protocol: TCP
      name: http
  selector:
    {{- include "oauth2-proxy.selectorLabels" . | nindent 4 }}
