{{- if and (not .Values.tunnelToken.existingSecret) .Values.tunnelToken.value -}}
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-tunnel-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.tunnelToken.value | quote }}
{{- end }}
