apiVersion: v2
name: jackett
description: API support for torrent trackers for Sonarr and Radarr
type: application
version: 0.1.0
appVersion: "0.21.0"
keywords:
  - jackett
  - indexer
  - torrent
  - sonarr
  - radarr
home: https://github.com/Jackett/Jackett
sources:
  - https://github.com/Jackett/Jackett
maintainers:
  - name: Kubarr Team
annotations:
  kubarr.io/display-name: "Jackett"
  kubarr.io/icon: "ğŸ”"
  kubarr.io/category: "indexer"
