{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "promtail.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "promtail.labels" . | nindent 4 }}
{{- end }}
