{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubarr.fullname" . }}
  labels:
    {{- include "kubarr.labels" . | nindent 4 }}
rules:
  {{- toYaml .Values.rbac.rules | nindent 2 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubarr.fullname" . }}
  labels:
    {{- include "kubarr.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubarr.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubarr.serviceAccountName" . }}
    namespace: {{ .Values.namespace.name }}
{{- end }}
