{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "victorialogs.serviceAccountName" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "victorialogs.labels" . | nindent 4 }}
{{- end }}
