apiVersion: v1
kind: Service
metadata:
  name: {{ include "victorialogs.fullname" . }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "victorialogs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.victorialogs.service.type }}
  ports:
    - port: {{ .Values.victorialogs.service.port }}
      targetPort: {{ .Values.victorialogs.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "victorialogs.selectorLabels" . | nindent 4 }}
