name: Test

on:
  workflow_call:
    inputs:
      image-tag:
        required: true
        type: string

jobs:
  backend:
    runs-on: self-hosted
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: kubarr-backend-test

      - name: Load image
        run: docker load < kubarr-backend-test.tar.gz

      - name: Unit tests
        run: docker run --rm "kubarr-backend-test:${{ inputs.image-tag }}" cargo test --verbose

  frontend:
    runs-on: self-hosted
    steps:
      - name: Download image artifact
        uses: actions/download-artifact@v4
        with:
          name: kubarr-frontend-test

      - name: Load image
        run: docker load < kubarr-frontend-test.tar.gz

      - name: Unit tests
        run: docker run --rm "kubarr-frontend-test:${{ inputs.image-tag }}" npm test

      - name: Build
        run: docker run --rm "kubarr-frontend-test:${{ inputs.image-tag }}" npm run build
